// import Image from "next/image"
import Header from "@/components/Header/Header"
import { Geist,Noto_Serif_Telugu } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const telugu3 = Noto_Serif_Telugu({
  variable: "--font-telugu3",
  subsets: ["latin"],
});

export const metadata = {
  title: 'Bench Playroom',
  description: 'Generated by kkkmr',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
      className={`${geistSans.className} ${telugu3.className}`}>
          <Header/>
          {children}
          <footer style={{ backgroundColor: 'lightgray', padding: '1rem' }}>
            <p>Footer</p>
          </footer>
        </body>
    </html>
  )
}
